---
title: "Iteration and list columns"
author: "Miriam Lachs"
date: "2024-10-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Here is sime lists

```{r}
l=list(
  vec_numeric = 1:4,
  unif_sample = runif(100),
  mat = matrix(1:8,nrow = 2,ncol = 4, byrow = TRUE),
  summary = summary(rnorm(1000))
)
l

l$mat

l[["mat"]][1,3]


l[[4]]
```


Make a list thats more useful

```{r}
list_norm =
  list(
    a=rnorm(20,0,5),
    b=rnorm(20,4,5),
    c=rnorm(20,0,10),
    d=rnorm(20,4,10)
  )


list_norm[['b']]
```

Let's reuse the function we wrote lastime 

```{r}
mean_and_sd = function(x){
  mean_x=mean(x)
  sd_x=sd(x)
  
  outdf=
    tibble(
      mean=mean_x,
      sd= sd_x
    )
  return(outdf)
}
```

LEt's use the function to take the mean and sd of all samples

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

## Use a for loop

Create output list and run a for loop 

```{r}
output = vector('list',length = 4)

for (i in 1:4) {
  output[[i]]= mean_and_sd(list_norm[[i]])
}

output
```


